version: '3.8'

services:
  db:
    build: ./db
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app


volumes:
  pgdata:
